[package]
name = "orka-cni"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cni-plugin = "0.2.1"
ipnet = { version = "2.8", features = ["serde"] }
log = "0.4.20"
# nix = "0.26.2"
