[package]
name = "network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnet = { version = "2.8.0", features = ["serde"] }
nix = "0.26.2"
serde = { version = "1.0.183", features = ["derive"] }
