[package]
name = "orka-proto"
description = "Protocol Buffers definitions for Orka gRPC services"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
prost = "0.11.9"
tonic = "0.9.2"

[build-dependencies]
prost-build = "0.11.9"
tonic-build = "0.9.2"
